### ISSUE TITLE
decode gets called multiple times (custom fields)

### ISSUE THREAD

**Issue by mabiede** [oxidizing/conformist#10]
Running conformist returns an error but the data gets still validated as expected.

The example record has three fields, a key, a language and a translation. The following lines are showing the output of the `decoder` function with additionally added loggers:
```
[INFO] [application]: confirmation_subject
[INFO] [application]: Something: Key
[INFO] [application]: Something: Language
[INFO] [application]: Something: Translation
[INFO] [application]: Empty list: Key
[INFO] [application]: Undefined key
[INFO] [application]: Something: Key
[INFO] [application]: Empty list: Language
[INFO] [application]: Undefined language
[INFO] [application]: Something: Language
[INFO] [application]: Empty list: Translation
[INFO] [application]: Undefined translation
[INFO] [application]: Something: Translation
```

Here is the custom decoder function (the empty list results in the "Undefined ..." message):
```
let decoder create_fcn field l =
  let open CCResult in
  match l with
  | x :: _ ->
    Logs.info (fun m -> m "Something: %s" (Entity_message.show_field field));
    create_fcn x
  | [] ->
    Logs.info (fun m -> m "Empty list: %s" (Entity_message.show_field field));
    Error (Entity_message.Undefined field |> with_log_error ~level:Logs.Info)
;;
```

It seems that conformist runs as expected in the first attempt and then tries to look for each field again (some recursiveness issue?).

**Comment by aronerben** [comment]
Fixed in https://github.com/oxidizing/conformist/commit/14b47284c44003180429f9e37e5fc5a3b75f73c9 => Reopen if issue persists
